os: linux
language: python
cache:
    directories:
        - $HOME/.cache/pip

python:
    - "3.6"

install:
    - pip install numpy Cython
    - pip install pytest coverage codecov
    - pip install -r requirements.txt
    - pip install -r docs/requirements.txt
    - pip install -e .

script:
    - python --version
    - coverage run -m py.test tests
    - coverage report -m
    - cd docs
    - make html
    - touch build/html/.nojekyll  # prevents use jekyll to build doc

# Push the results back to codecov
after_success:
    - bash <(curl -s https://codecov.io/bash)

deploy:
    provider: pages
    skip_cleanup: true
    keep_history: false
    github_token: $GITHUB_PAGES
    local_dir: docs/build/html
    on:
      branch: master, improve_docs
